import type { Metadata } from 'next';
import { hostGrotesk, funnelDisplay } from '@/lib/fonts/fonts';
import './globals.css';
import MenuButton from '@/components/ui/menu-button';
import ScrollWidget from '@/components/ui/scroll-widget';

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body style={{ backgroundColor: 'hsl(0, 0%, 5%)' }} className={`${hostGrotesk} ${funnelDisplay} antialiased`}>
				<>
					<MenuButton />
					{children}
					<ScrollWidget />
				</>
			</body>
		</html>
	);
}
